# Generated by Django 5.1.3 on 2025-04-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('protein', models.DecimalField(decimal_places=3, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=3, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=3, max_digits=5)),
                ('vitamins', models.DecimalField(decimal_places=3, max_digits=5)),
                ('minerals', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
